version: 2
updates:
- package-ecosystem: pip
  directory: "/python/requirements/CI-complete"
  rebase-strategy: disabled
  schedule:
    interval: weekly
  labels:
    - dependancy-upgrade
- package-ecosystem: pip
  directory: "/python/requirements/CI-docs"
  rebase-strategy: disabled
  schedule:
    interval: weekly
  labels:
    - dependancy-upgrade
- package-ecosystem: pip
  directory: "/python/requirements/CI-tests-conda"
  rebase-strategy: disabled
  schedule:
    interval: weekly
  labels:
    - dependancy-upgrade
- package-ecosystem: pip
  directory: "/python/requirements/CI-tests-pip"
  rebase-strategy: disabled
  schedule:
    interval: weekly
  labels:
    - dependancy-upgrade
