coverage:
  status:
    project:
      python-tests:
        target: 95%
        flags: python_tests
      python-c-tests:
        target: 85%
        flags: python_c_tests
      c-tests:
        target: 85%
        flags: c_tests
