environment:
  matrix:
    # We only test on one Python version as builds are slow and sequential.
    - PYTHON_VERSION: "3.7"

init:
  - cmd: SET PYTHON=C:\\Miniconda37-x64
  - cmd: ECHO Using %PYTHON%
  - cmd: ECHO Cores %NUMBER_OF_PROCESSORS%

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - cmd: git submodule update --init --recursive
  # We have symlinks in the repo, which need to be treated specially on Windows.
  - cmd: git config core.symlinks true
  - cmd: git reset --hard
  - cmd: conda config --add channels conda-forge
  - cmd: conda create --yes -n testenv python=%PYTHON_VERSION%
  - cmd: activate testenv
  - cmd: conda install --yes --file=python\requirements\conda-minimal.txt
  - cmd: conda info -a
  - cmd: python --version

build_script:
  - cmd: cd python
  - cmd: python setup.py build_ext --inplace
  # Install some modules needed for tests
  - cmd: python -m pip install -r requirements/appveyor-pypi.txt
  - cmd: python -m pytest -n %NUMBER_OF_PROCESSORS%

after_test:
  - cmd: python setup.py bdist_wheel
